#!/usr/bin/env bash
# Play games with a task's pretrained checkpoint (from MODEL_REGISTRY in
# qlearningAgents.py) purely to collect memory-unit training data: every
# step is appended to pacman/data/piezas_task_<difficulty> (paper Section
# 5's "20 thousand data points drawn from trajectories generated by the
# best model for its task"). Run this once for task 0 and once for task 1
# before scripts/train_memory_unit.sh.
#
# Usage: scripts/collect_memory_data.sh <difficulty:0|1> [num_games]
set -euo pipefail

DIFFICULTY="${1:?usage: $0 <difficulty:0|1> [num_games]}"
NUM_GAMES="${2:-1000}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/../pacman"

# -x 0: no further training, the agent runs the MODEL_REGISTRY checkpoint
# for this difficulty greedily (epsilon=0.1) in data-collection mode.
python pacman.py -p PacmanQAgent -g DirectionalGhost \
    -d "$DIFFICULTY" -x 0 -n "$NUM_GAMES"

echo
echo "Collected data written to pacman/data/piezas_task_${DIFFICULTY}"
